name: build-web

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: IonutParau
          repository: thepuzzlecell
      - run: |
          ls -la
          echo "CLONED REPO"
          cd thepuzzlecell
          ls -la
      - run: cd thepuzzlecell;pwd
      - run: cd thepuzzlecell;ls
      - run: cd thepuzzlecell;flutter pub get
      - run: cd thepuzzlecell;flutter build web
      - uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: thepuzzlecell/build/windows/runner/Release
